### ISSUE TITLE
log.Fatal is will terminate the application making os.Exit pointless.

### ISSUE THREAD

**Issue by badgersec** [FKouhai/GoBotMan#6]
https://github.com/FKouhai/GoBotMan/blob/1d50354df71983407de8ae042d0c55e607424f86/agent/agent.go#L35

**Comment by badgersec** [comment]
https://github.com/FKouhai/GoBotMan/blob/1d50354df71983407de8ae042d0c55e607424f86/agent/agent.go#L27

**Comment by FKouhai** [comment]
Fixed in d08651c9f51e72eb5dc617680692f9bbecf0e9bd
