### ISSUE TITLE
fmt.Fprintln

### ISSUE THREAD

**Issue by badgersec** [FKouhai/GoBotMan#8]
https://github.com/FKouhai/GoBotMan/blob/1d50354df71983407de8ae042d0c55e607424f86/agent/agent.go#L51

**Comment by badgersec** [comment]
https://github.com/FKouhai/GoBotMan/blob/1d50354df71983407de8ae042d0c55e607424f86/agent/agent.go#L57

**Comment by FKouhai** [comment]
Fixed in d08651c9f51e72eb5dc617680692f9bbecf0e9bd
